### ISSUE TITLE
Can't touch on video when full screen

### ISSUE THREAD

**Issue by anhnt92** [changsanjiang/SJBaseVideoPlayer#2]
Can you check this class code for me.
`    _videoPlayer = [SJVideoPlayer player];

    if (globals.currModelVideo.typepost == 1){
        [self.playView.heightAnchor constraintEqualToAnchor:self.playView.widthAnchor multiplier: 9.0/16.0].active = true;
        CGRect frame = self.playView.frame;
        _videoPlayer.view.frame = CGRectMake(0, 0, frame.size.width, frame.size.width/16*9);

    }else{
        if (globals.currModelVideo.width<=0){
                    [self.playView.heightAnchor constraintEqualToAnchor:self.playView.widthAnchor multiplier: 9.0/16].active = true;
            CGRect frame = self.playView.frame;
            _videoPlayer.view.frame = CGRectMake(0, 0, frame.size.width, frame.size.width/16*9);
        }else{
                    [self.playView.heightAnchor constraintEqualToAnchor:self.playView.widthAnchor multiplier: globals.currModelVideo.height/globals.currModelVideo.width].active = true;
            CGRect frame = self.playView.frame;
            _videoPlayer.view.frame = CGRectMake(0, 0, frame.size.width, frame.size.width/globals.currModelVideo.width*globals.currModelVideo.height);
        }
    }

    [_videoPlayer setDisableGestureTypes:SJDisablePlayerGestureTypes_DoubleTap];
    [_videoPlayer setDisableVolumeSetting:YES];
    [_videoPlayer setDisableBrightnessSetting:YES];
    _videoPlayer.controlLayerDelegate = self;
    if (_type_post == 2){
        [_videoPlayer hideForGIF];
    }
    _videoPlayer.view.alpha = 0.001;
    _videoPlayer.delegate = self;

    [self.playView.superview addSubview:_videoPlayer.view];
    

    [UIView animateWithDuration:0.5 animations:^{
        _videoPlayer.view.alpha = 1;
    }];`

I don't know why?Thanks.

**Comment by changsanjiang** [comment]
How do you rotate into full screen?

**Comment by anhnt92** [comment]
It rotate by default, in SJVideoPlayerDefaultControlView. i do nothing. I just have skype.

**Comment by changsanjiang** [comment]
```Objective-C
[_videoPlayer setDisableGestureTypes:SJDisablePlayerGestureTypes_DoubleTap];
[_videoPlayer setDisableVolumeSetting:YES];
[_videoPlayer setDisableBrightnessSetting:YES];
_videoPlayer.controlLayerDelegate = self;
```
You can try to delete the `_videoPlayer.controlLayerDelegate = self;`

**Comment by changsanjiang** [comment]
Can I see all the code for this controller?

**Comment by anhnt92** [comment]
You can download here : [https://secufiles.com/5l25/TGCommentVC.m](url)

**Comment by changsanjiang** [comment]
OK.

**Comment by changsanjiang** [comment]
Give me a little time, I study it.

**Comment by anhnt92** [comment]
THanks.

**Comment by changsanjiang** [comment]
You can try to delete the code. Run it.

```Objective-C
    _observer = [[SJOrentationObserver alloc] initWithTarget:self.view container:self.view.superview];
    
    // must imp it.
    _observer.rotationCondition = ^BOOL(SJOrentationObserver * _Nonnull observer) {
        return YES;
    };
```
And
```Objective-C
-(BOOL)shouldAutorotate
{
    return _isShouldRotate;
}

-(UIInterfaceOrientationMask)supportedInterfaceOrientations
{
    return UIInterfaceOrientationMaskAll;
}
```

**Comment by anhnt92** [comment]
Its not work. Please help me.

**Comment by changsanjiang** [comment]
Do you have Twitter?

**Comment by changsanjiang** [comment]
changsanjiang is me.

**Comment by anhnt92** [comment]
Yes, i have. "anhnt592"
