### ISSUE TITLE
endGeneratingDeviceOrientationNotifications 没有调用可能导致 iOS 13.x crash 

### ISSUE THREAD

**Issue by ACFancy** [changsanjiang/SJBaseVideoPlayer#25]
###  问题
 - 在SJRotationManager类中，没有保证 beginGeneratingDeviceOrientationNotifications 和 endGeneratingDeviceOrientationNotifications 成对调用。可能导致iOS 13.x crash
### 参考
- [stackoverflow issue](https://stackoverflow.com/q/8887851)
- [博客](https://15tar.com/%E6%8A%80%E6%9C%AF/2019/12/28/threading-violation-expected-the-main-thread.html)

**Comment by ACFancy** [comment]
@changsanjiang

**Comment by changsanjiang** [comment]
我看看

**Comment by ACFancy** [comment]
@changsanjiang 可以参考下这个库的PR: [PR](https://github.com/QuintGao/GKPhotoBrowser/pull/72)

**Comment by changsanjiang** [comment]
他这个应该解决的是 多次调用开启通知的问题。  咱们不需要， [开启之前](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/ba64ec18d7fcc6f47cd81ce573ebd436f6583312/SJBaseVideoPlayer/Common/Implements/SJRotationManager.m#L326)已经做了相应判断了。

**Comment by ACFancy** [comment]
@changsanjiang 开启前是做了判断，但是begin和end并没有成对出现吧? 如果是自己主动开启的，还是要满足条件自己主动关闭掉吧？

**Comment by ACFancy** [comment]
> 他这个应该解决的是 多次调用开启通知的问题。 咱们不需要， [开启之前](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/ba64ec18d7fcc6f47cd81ce573ebd436f6583312/SJBaseVideoPlayer/Common/Implements/SJRotationManager.m#L326)已经做了相应判断了。上面提及的PR通知只是他们的一部分，还有一部分是begin和end的

**Comment by changsanjiang** [comment]
通常不需要关闭它， 因为我们一直要监听设备方向变化的， 关闭之后就收不到了。

比方App 会创建很多个播放器， 一旦某个播放器关闭通知， 其他播放器的旋转管理类就收不到通知了。
