### ISSUE TITLE
隐藏画中画按钮代码怎么无效啊。

### ISSUE THREAD

**Issue by developerjet** [changsanjiang/SJBaseVideoPlayer#26]
[self.topAdapter removeItemForTag:SJEdgeControlLayerTopItem_PictureInPicture];
您好，请问通过这段代码设置隐藏画中画按钮，怎么无效。

**Comment by changsanjiang** [comment]
这个按钮由控制层控制了， 设置对应属性隐藏

https://github.com/changsanjiang/SJVideoPlayer/wiki/%E6%8E%A7%E5%88%B6%E5%B1%82%E5%8F%B3%E4%B8%8A%E8%A7%92%E7%9A%84%E5%9B%BE%E6%A0%87-%E6%80%8E%E4%B9%88%E9%9A%90%E8%97%8F%3F

**Comment by developerjet** [comment]
> 这个按钮由控制层控制了， 设置对应属性隐藏
> 
> https://github.com/changsanjiang/SJVideoPlayer/wiki/%E6%8E%A7%E5%88%B6%E5%B1%82%E5%8F%B3%E4%B8%8A%E8%A7%92%E7%9A%84%E5%9B%BE%E6%A0%87-%E6%80%8E%E4%B9%88%E9%9A%90%E8%97%8F%3F

好的，谢谢了
