### ISSUE TITLE
子视图没有被添加到父视图上，调动Masonry布局时崩溃

### ISSUE THREAD

**Issue by ElvistLui** [changsanjiang/SJBaseVideoPlayer#28]
![image](https://user-images.githubusercontent.com/21191640/169180142-d2e5ecfa-ba8b-4936-9a05-0a7e53dcd422.png)

<img width="791" alt="image" src="https://user-images.githubusercontent.com/21191640/169180223-0d927caf-02a3-433a-affa-0b5d374097ee.png">

**Comment by changsanjiang** [comment]
已修复
