### ISSUE TITLE
Logo Design Offer as Open Source Contribution 

### ISSUE THREAD

**Issue by anharismail** [changsanjiang/SJBaseVideoPlayer#3]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see a new open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by changsanjiang** [comment]
it sounds great, is it for free?

**Comment by anharismail** [comment]
Thanks for your response @changsanjiang , It's free as my contribution on open source project.

**Comment by changsanjiang** [comment]
Thanks for yours logo! I can't wait to see it? When you can complete it?

**Comment by anharismail** [comment]
As soon as possible on the next few days I'll provide my logo @changsanjiang

**Comment by anharismail** [comment]
Hello @changsanjiang , this is my logo proposal for your project.
This logo was inspired by play element.

I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

![sjbase video player ver 1](https://user-images.githubusercontent.com/37614260/43504157-7c1f87e4-958c-11e8-9d64-9ea6b5384b60.png)

**Comment by anharismail** [comment]
hello @changsanjiang , is there any response to my logo proposal?

**Comment by changsanjiang** [comment]
Hello @anharismail 
Thanks for your designs.
I want to use it  in [SJVideoPlayer](https://github.com/changsanjiang/SJVideoPlayer), but i can't use because this design comes with `SJBaseVideoPlayer`.

**Comment by anharismail** [comment]
Hi @changsanjiang , thanks for the response. I did like that to follow this repository. But no problem, I can edit it to appropriate with SJVideoPlayer
