### ISSUE TITLE
tableview 自动播放视频

### ISSUE THREAD

**Issue by zt1993** [changsanjiang/SJBaseVideoPlayer#4]
你好，我用了你另一个里面的SJBaseVideoPlayer 去加在tableview中，我的cell 是有的cell有视频，有的没有，我看了你的demo，不是特别明白tableview是怎么实现自动播放的，想请问下有详细的说明可以看一下吗

**Comment by changsanjiang** [comment]
正常配置就可以
当前显示的cell中, 没有视频可以播放的时候, 就不会播放了

**Comment by zt1993** [comment]
我是应该按照你另一个文件中 ViewControllerTableViewAutoPlay  这个类 来配置么？因为我是要转到swift，今天按这个类配了一下，一直crash

**Comment by changsanjiang** [comment]
可否提供一下截图, 我看看报什么错

**Comment by zt1993** [comment]
额，明天给您吧，今天感觉配的有点乱，我明天再试试，先谢谢了，另外，感谢提供这个组件，定制化很高，很厉害

**Comment by changsanjiang** [comment]
好的, 不客气👌

**Comment by zt1993** [comment]
另外，我好像发现了个问题，我自己定义了控制层，加了slider，但是我的slider好像被你视图上的移动手势覆盖了，这是为什么

**Comment by changsanjiang** [comment]
可以在代理方法中, 返回NO, 不触发手势
![image](https://user-images.githubusercontent.com/25744224/48546162-9a232100-e902-11e8-9a42-6dfd3f4b9f6f.png)

**Comment by zt1993** [comment]
这个我看到了，但是因为我们全屏的时候我是需要移动的这个手势的，我看你的demo里进度条的手势和屏幕上的移动手势是共存的，是因为你的进度条另外加了个层么

**Comment by zt1993** [comment]
嗯，刚好准备按这个方法来写，谢谢了，可以加个您的联系方式嘛

**Comment by changsanjiang** [comment]
加我的QQ吧  1779609779

**Comment by zt1993** [comment]
你好，我加你了，可以通过一下吗
