### ISSUE TITLE
审核会被拒

### ISSUE THREAD

**Issue by sunzhe** [changsanjiang/SJBaseVideoPlayer#5]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "". Please correct the following issues, then upload again.

Non-public API usage:

The app references non-public selectors in GK: appDidBecomeActive:, appDidEnterBackground:, appWillResignActive:, closeButtonPressed:, didShowViewController:animated:
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.

Best regards,

The App Store Team

**Comment by changsanjiang** [comment]
👌.  appDidBecomeActive:, appDidEnterBackground:, appWillResignActive:, 这三个方法名确实存在,  我修改一下名字.
