### ISSUE TITLE
autoDisappearFloatSmallView 设置无效

### ISSUE THREAD

**Issue by sheodon** [changsanjiang/SJBaseVideoPlayer#8]
设置 autoDisappearFloatSmallView 为 YES时, 播放结束后, 小浮窗没有隐藏

**Comment by changsanjiang** [comment]
收到,  是个bug,  下个版本修复

**Comment by changsanjiang** [comment]
@sheodon 先修改一下源码吧

![image](https://user-images.githubusercontent.com/25744224/70502196-12d2cc00-1b5b-11ea-8992-9a0ff9d63d97.png)

**Comment by sheodon** [comment]
> @sheodon 先修改一下源码吧
> 
> ![image](https://user-images.githubusercontent.com/25744224/70502196-12d2cc00-1b5b-11ea-8992-9a0ff9d63d97.png)

好的，谢谢
